const LEGAL_CONTACT_EMAIL = "sharmaji582009@gmail.com"
const LEGAL_CONTACT_URL = `mailto:${LEGAL_CONTACT_EMAIL}`
const LEGAL_LAST_UPDATED = "September 24, 2026"
const LEGAL_LAST_UPDATED_ISO = "2026-09-24"
const PRIVACY_LAST_UPDATED = "September 24, 2026"
const PRIVACY_LAST_UPDATED_ISO = "2026-09-24"

export {
  LEGAL_CONTACT_EMAIL,
  LEGAL_CONTACT_URL,
  LEGAL_LAST_UPDATED,
  LEGAL_LAST_UPDATED_ISO,
  PRIVACY_LAST_UPDATED,
  PRIVACY_LAST_UPDATED_ISO,
}
